version: '3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: database-pb2.cpy1vk3kgfvg.us-east-1.rds.amazonaws.com
      WORDPRESS_DB_USER: adminpb
      WORDPRESS_DB_PASSWORD: teste123
      WORDPRESS_DB_NAME: database-pb2
